# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meu blog pessoal
email: marcelogelati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este é meu blog pessoal para compartilhar assuntos de meu interesse,
  A princípio, era para postar coisas acadêmicas que tangenciavam mais ou menos economia,
  mas hoje pretendo postar qualquer coisa que tiver vontade de postar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "marcelogelati.github.io" # the base hostname & protocol for your site
github_username:  marcelogelati

# Build settings
markdown: kramdown
